#!/bin/sh

uci set network.lan.ipaddr='172.16.32.8'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='172.16.32.1'
uci set network.lan.dns='172.16.32.1'
uci commit network
/etc/init.d/network restart
uci set dropbear.main.PasswordAuth='on'
uci set dropbear.main.Port='22'
uci set dropbear.main.Interface='lan'
uci commit dropbear
/etc/init.d/dropbear restart
uci set network.lan.ip6assign='0'
uci set network.wan.ip6assign='0'
uci set network.globals.ipv6='0'
uci set dhcp.lan.ignore='1'
uci set dhcp.lan.ra='0'
uci commit network
uci commit dhcp
/etc/init.d/network restart
